# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import libros.models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='static/default_book.png', null=True, storage=libros.models.get_image_path, upload_to=libros.models.get_image_path),
        ),
    ]
