# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulos',
            options={'verbose_name': 'Capitulo', 'verbose_name_plural': 'Capitulos'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='libros',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RenameField(
            model_name='libros',
            old_name='data_creacio',
            new_name='data_creacion',
        ),
    ]
