# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20190506_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='data_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
