# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import libros.models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_capitulos_data_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='generos',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='/static/default_book.png', null=True, upload_to=libros.models.get_image_path),
        ),
    ]
