# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20190514_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='contenido',
            field=models.TextField(max_length=100),
        ),
    ]
