# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20190515_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='contenido',
            field=models.TextField(),
        ),
    ]
