# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_generos_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='generos',
            field=models.ManyToManyField(blank=True, null=True, to='libros.Generos'),
        ),
    ]
