# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_auto_20190509_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generos',
            name='imagen_perfil',
        ),
    ]
