# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20190521_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
