# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0010_auto_20190509_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitulos',
            old_name='data_creacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='libros',
            old_name='data_creacion',
            new_name='fecha_creacion',
        ),
    ]
