# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='static/default_profile.png', null=True, storage=usuarios.models.get_image_path, upload_to=usuarios.models.get_image_path),
        ),
    ]
