# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_auto_20190521_1341'),
        ('usuarios', '0003_auto_20190514_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosSeguidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_capitulo', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
            options={
                'verbose_name': 'Libros seguidos',
                'verbose_name_plural': 'Libros seguidos',
            },
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
