# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190506_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='/static/default_profile.png', null=True, upload_to=usuarios.models.get_image_path),
        ),
    ]
