# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20190523_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='librosseguidos',
            name='ultima_visita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
